apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1b0705616d8b4b8639c93936dc08103c8d2a447f
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad2-TELP
  labels:
    app.kubernetes.io/instance: emea8-squad2-telp
    app.kubernetes.io/name: emea8-squad2-telp
  name: emea8-squad2-telp
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app.kubernetes.io/instance: emea8-squad2-telp
    app.kubernetes.io/name: emea8-squad2-telp
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1b0705616d8b4b8639c93936dc08103c8d2a447f
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad2-TELP
  labels:
    app.kubernetes.io/instance: emea8-squad2-telp
    app.kubernetes.io/name: emea8-squad2-telp
  name: emea8-squad2-telp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: emea8-squad2-telp
      app.kubernetes.io/name: emea8-squad2-telp
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 1b0705616d8b4b8639c93936dc08103c8d2a447f
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad2-TELP
      labels:
        app.kubernetes.io/instance: emea8-squad2-telp
        app.kubernetes.io/name: emea8-squad2-telp
    spec:
      containers:
      - image: quay.io/pbworker/telp-app:1b0705616d8b4b8639c93936dc08103c8d2a447f
        name: emea8-squad2-telp
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1b0705616d8b4b8639c93936dc08103c8d2a447f
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad2-TELP
  labels:
    app.kubernetes.io/instance: emea8-squad2-telp
    app.kubernetes.io/name: emea8-squad2-telp
  name: emea8-squad2-telp
spec:
  to:
    kind: Service
    name: emea8-squad2-telp
